### ISSUE TITLE
pallocs in critical section during insert

### ISSUE THREAD

**Issue by dAdAbird** [Percona-Lab/postgres-tde-ext#33]
With the changes in https://github.com/Percona-Lab/postgres-tde-ext/commit/25fa6df69b3144bc6fccc633c7b1152c959b5a01 an internal key being fetched on each encrypt/decrypt op. Sometimes it happens in a critical section (e.g. for a [tuple insert](https://github.com/Percona-Lab/postgres-tde-ext/blob/25fa6df69b3144bc6fccc633c7b1152c959b5a01/src/access/pg_tdeam.c#L1879-L1881)). And if the key is not in the cache, TDE will try to get it from the fork file. This in turn leads to several pallocs - one inside the PG's `relpathperm()` (construct the fork path) and another for retrieved keys itself. But `palloc` (and `MemoryContextAlloc` for that matter) have `AssertNotInCriticalSection()`:
```
/*
 * You should not do memory allocations within a critical section, because
 * an out-of-memory error will be escalated to a PANIC. To enforce that
 * rule, the allocation functions Assert that.
 */
```

If postgres is built with asserts, every insert into a new table leads to a crash:
```
TRAP: failed Assert("CritSectionCount == 0 || (context)->allowInCritSection"), File: "../src/backend/utils/mmgr/mcxt.c", Line: 1233, PID: 77049
0   postgres                            0x0000000100e6a3fd ExceptionalCondition + 189
1   postgres                            0x0000000100eb26fc palloc + 172
2   postgres                            0x0000000100eed4b2 psprintf + 146
3   postgres                            0x0000000100eedabb GetRelationPath + 299
4   pg_tde.dylib                        0x000000010ac17865 pg_tde_get_key_file_path + 53
5   pg_tde.dylib                        0x000000010ac17c2c pg_tde_get_keys_from_fork + 28
6   pg_tde.dylib                        0x000000010ac17f63 GetRelationKeys + 131
7   pg_tde.dylib                        0x000000010ac466ed PGTdePageAddItemExtended + 157
8   pg_tde.dylib                        0x000000010ac3741a pg_tde_RelationPutHeapTuple + 298
9   pg_tde.dylib                        0x000000010ac1ae39 pg_tde_insert + 265
10  pg_tde.dylib                        0x000000010ac2ce67 pg_tdeam_tuple_insert + 103
11  postgres                            0x00000001009e5560 table_tuple_insert + 64
12  postgres                            0x00000001009e0bd7 ExecInsert + 2407
13  postgres                            0x00000001009def67 ExecModifyTable + 1991
14  postgres                            0x000000010099e552 ExecProcNodeFirst + 82
15  postgres                            0x0000000100995f52 ExecProcNode + 50
16  postgres                            0x0000000100991211 ExecutePlan + 209
17  postgres                            0x00000001009910ab standard_ExecutorRun + 571
18  postgres                            0x0000000100990e62 ExecutorRun + 98
19  postgres                            0x0000000100c57205 ProcessQuery + 133
20  postgres                            0x0000000100c56143 PortalRunMulti + 451
21  postgres                            0x0000000100c55742 PortalRun + 962
22  postgres                            0x0000000100c50ad8 exec_simple_query + 1464
23  postgres                            0x0000000100c4fb92 PostgresMain + 2258
24  postgres                            0x0000000100b63922 BackendRun + 50
25  postgres                            0x0000000100b611fc BackendStartup + 524
26  postgres                            0x0000000100b5eb0e ServerLoop + 350
27  postgres                            0x0000000100b5d763 PostmasterMain + 6803
28  postgres                            0x0000000100a2bdc2 main + 818
29  dyld                                0x000000020174941f start + 1903
```
gdb backtrace:
```
#0  __pthread_kill_implementation (threadid=281473813631008, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x0000ffffb9bff254 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x0000ffffb9bba67c in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x0000ffffb9ba7130 in __GI_abort () at ./stdlib/abort.c:79
#4  0x0000aaaad55d8980 in ExceptionalCondition (conditionName=0xaaaad582a340 "CritSectionCount == 0 || (context)->allowInCritSection", fileName=0xaaaad5829f20 "../src/backend/utils/mmgr/mcxt.c", lineNumber=1233)
    at ../src/backend/utils/error/assert.c:66
#5  0x0000aaaad561e64c in palloc (size=128) at ../src/backend/utils/mmgr/mcxt.c:1233
#6  0x0000aaaad5656064 in psprintf (fmt=0xaaaad584a4d0 "base/%u/%u") at ../src/common/psprintf.c:61
#7  0x0000aaaad5656588 in GetRelationPath (dbOid=16388, spcOid=1663, relNumber=114699, backendId=-1, forkNumber=MAIN_FORKNUM) at ../src/common/relpath.c:167
#8  0x0000ffffb6e197b4 in pg_tde_get_key_file_path (newrlocator=0xffffdea495b0) at ../contrib/postgres-tde-ext/src/access/pg_tde_tdemap.c:231
#9  0x0000ffffb6e193e8 in pg_tde_get_keys_from_fork (rlocator=0xffffdea495b0) at ../contrib/postgres-tde-ext/src/access/pg_tde_tdemap.c:116
#10 0x0000ffffb6e19660 in GetRelationKeys (rel=...) at ../contrib/postgres-tde-ext/src/access/pg_tde_tdemap.c:193
#11 0x0000ffffb6e46cac in PGTdePageAddItemExtended (rel=..., oid=114699, bn=20, page=0xffffae681000 "", item=0xaaaae5e67550 "\033\003", size=80, offsetNumber=0, flags=2)
    at ../contrib/postgres-tde-ext/src/encryption/enc_tuple.c:119
#12 0x0000ffffb6e386cc in pg_tde_RelationPutHeapTuple (relation=0xffffadd28488, buffer=129, tuple=0xaaaae5e67538, token=false) at ../contrib/postgres-tde-ext/src/access/pg_tde_io.c:66
#13 0x0000ffffb6e1d134 in pg_tde_insert (relation=0xffffadd28488, tup=0xaaaae5e67538, cid=0, options=0, bistate=0x0) at ../contrib/postgres-tde-ext/src/access/pg_tdeam.c:1881
#14 0x0000ffffb6e2f460 in pg_tdeam_tuple_insert (relation=0xffffadd28488, slot=0xaaaae5e74928, cid=0, options=0, bistate=0x0) at ../contrib/postgres-tde-ext/src/access/pg_tdeam_handler.c:262
#15 0x0000aaaad5194a9c in table_tuple_insert (rel=0xffffadd28488, slot=0xaaaae5e74928, cid=0, options=0, bistate=0x0) at ../src/include/access/tableam.h:1400
#16 0x0000aaaad5196a20 in ExecInsert (context=0xffffdea499a0, resultRelInfo=0xaaaae5e65b78, slot=0xaaaae5e74928, canSetTag=true, inserted_tuple=0x0, insert_destrel=0x0) at ../src/backend/executor/nodeModifyTable.c:1133
#17 0x0000aaaad519ac00 in ExecModifyTable (pstate=0xaaaae5e65968) at ../src/backend/executor/nodeModifyTable.c:3790
#18 0x0000aaaad5156380 in ExecProcNodeFirst (node=0xaaaae5e65968) at ../src/backend/executor/execProcnode.c:464
#19 0x0000aaaad5149828 in ExecProcNode (node=0xaaaae5e65968) at ../src/include/executor/executor.h:273
#20 0x0000aaaad514c7d4 in ExecutePlan (estate=0xaaaae5e656d8, planstate=0xaaaae5e65968, use_parallel_mode=false, operation=CMD_INSERT, sendTuples=false, numberTuples=0, direction=ForwardScanDirection, dest=0xaaaae5e71f78,
    execute_once=true) at ../src/backend/executor/execMain.c:1670
#21 0x0000aaaad5149f80 in standard_ExecutorRun (queryDesc=0xaaaae5db6138, direction=ForwardScanDirection, count=0, execute_once=true) at ../src/backend/executor/execMain.c:365
#22 0x0000aaaad5149d78 in ExecutorRun (queryDesc=0xaaaae5db6138, direction=ForwardScanDirection, count=0, execute_once=true) at ../src/backend/executor/execMain.c:309
#23 0x0000aaaad53e654c in ProcessQuery (plan=0xaaaae5e71e18, sourceText=0xaaaae5d8dd38 "INSERT INTO pvactst SELECT i, array[1,2,3], point(i, i+1) FROM generate_series(1,1000) i;", params=0x0, queryEnv=0x0, dest=0xaaaae5e71f78,
    qc=0xffffdea49e48) at ../src/backend/tcop/pquery.c:160
#24 0x0000aaaad53e8060 in PortalRunMulti (portal=0xaaaae5e0a0e8, isTopLevel=true, setHoldSnapshot=false, dest=0xaaaae5e71f78, altdest=0xaaaae5e71f78, qc=0xffffdea49e48) at ../src/backend/tcop/pquery.c:1277
#25 0x0000aaaad53e7518 in PortalRun (portal=0xaaaae5e0a0e8, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0xaaaae5e71f78, altdest=0xaaaae5e71f78, qc=0xffffdea49e48) at ../src/backend/tcop/pquery.c:791
#26 0x0000aaaad53decb0 in exec_simple_query (query_string=0xaaaae5d8dd38 "INSERT INTO pvactst SELECT i, array[1,2,3], point(i, i+1) FROM generate_series(1,1000) i;") at ../src/backend/tcop/postgres.c:1274
#27 0x0000aaaad53e43ac in PostgresMain (dbname=0xaaaae5dc7e90 "vagrant", username=0xaaaae5dc7e78 "vagrant") at ../src/backend/tcop/postgres.c:4637
#28 0x0000aaaad52f87b0 in BackendRun (port=0xaaaae5db7e20) at ../src/backend/postmaster/postmaster.c:4464
#29 0x0000aaaad52f80ac in BackendStartup (port=0xaaaae5db7e20) at ../src/backend/postmaster/postmaster.c:4192
#30 0x0000aaaad52f3918 in ServerLoop () at ../src/backend/postmaster/postmaster.c:1782
#31 0x0000aaaad52f30f4 in PostmasterMain (argc=1, argv=0xaaaae5ccca90) at ../src/backend/postmaster/postmaster.c:1466
#32 0x0000aaaad51de790 in main (argc=1, argv=0xaaaae5ccca90) at ../src/backend/main/main.c:198
```

**Comment by dAdAbird** [comment]
In addition to https://github.com/Percona-Lab/postgres-tde-ext/pull/34 we also have to populate the cache from *.tde forks on process init.
